<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>SkyPilot.App</RootNamespace>
    <AssemblyName>SkyPilot</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\SkyPilot.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\mark.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SkyNetwork.Voice\SkyNetwork.Voice.csproj" />
    <ProjectReference Include="..\SkyPilot.Core\SkyPilot.Core.csproj" />
    <ProjectReference Include="..\SkyPilot.SimConnect\SkyPilot.SimConnect.csproj" />
  </ItemGroup>
</Project>
